### ISSUE TITLE
Crash Message

### ISSUE THREAD

**Issue by pivetta1975** [fortinet/ibm-fortigate-AP-HA-terraform-deploy#4]
I tried to deploy fortigate firewalls on my VPC environment and I received crash message. Could you help about this issue ?

[Terraform_log.pdf](https://github.com/fortinet/ibm-fortigate-AP-HA-terraform-deploy/files/6695221/Terraform_log.pdf)

**Comment by Joel-Cripps** [comment]
Can you paste the error into the comment field? You can use  three backticks to create a block.

https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by pivetta1975** [comment]
> I tried to deploy fortigate firewalls on my VPC environment and I received crash message. Could you help about this issue ?
> 
> [Terraform_log.pdf](https://github.com/fortinet/ibm-fortigate-AP-HA-terraform-deploy/files/6695221/Terraform_log.pdf)

**Comment by pivetta1975** [comment]
> I tried to deploy fortigate firewalls on my VPC environment and I received crash message. Could you help about this issue ?
> 
> [Terraform_log.pdf](https://github.com/fortinet/ibm-fortigate-AP-HA-terraform-deploy/files/6695221/Terraform_log.pdf)

Error

 2021/06/21 12:23:33 Terraform apply | 
 2021/06/21 12:23:33 Terraform apply | Error: rpc error: code = Unavailable desc = transport is closing
 2021/06/21 12:23:33 Terraform apply | 
 2021/06/21 12:23:33 Terraform apply | 
 2021/06/21 12:23:33 Terraform apply | 
 2021/06/21 12:23:33 Terraform apply | Error: rpc error: code = Unavailable desc = transport is closing
 2021/06/21 12:23:33 Terraform apply | 
 2021/06/21 12:23:33 Terraform apply | 
 2021/06/21 12:23:33 Terraform apply | panic: runtime error: invalid memory address or nil pointer dereference
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: [signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0xd5314f]
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: goroutine 727 [running]:
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/client.(*Client).MakeRequest(0xc000f0d6c0, 0xc000b4cf68, 0x20c1540, 0xc0007f9dc0, 0x0, 0x0, 0x0)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/client/client.go:108 +0x36f
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/client.(*Client).tryHTTPRequest(0xc000f0d6c0, 0x5, 0x12a05f200, 0xc000b4cf68, 0x20c1540, 0xc0007f9dc0, 0xc000f18000, 0xc000c38050, 0xc000531313)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/client/client.go:124 +0x56
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/client.(*Client).tryHTTPRequest(0xc000f0d6c0, 0x5, 0x12a05f200, 0xc000b4cf68, 0x20c1540, 0xc0007f9dc0, 0xc00053ba70, 0xc000c38050, 0xc000f11313)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/client/client.go:134 +0x17d
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/client.(*Client).tryHTTPRequest(0xc000f0d6c0, 0x6, 0x12a05f200, 0xc000b4cf68, 0x20c1540, 0xc0007f9dc0, 0xc000f18000, 0xc000c38050, 0xc000201313)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/client/client.go:134 +0x17d
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/client.(*Client).tryHTTPRequest(0xc000f0d6c0, 0x7, 0x12a05f200, 0xc000b4cf68, 0x20c1540, 0xc0007f9dc0, 0xc00020f3b0, 0xc000c38050, 0xc000201313)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/client/client.go:134 +0x17d
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/client.(*Client).tryHTTPRequest(0xc000f0d6c0, 0x8, 0x12a05f200, 0xc000b4cf68, 0x20c1540, 0xc0007f9dc0, 0xc00020e000, 0xc000091400, 0x0)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/client/client.go:134 +0x17d
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/client.(*Client).tryHTTPRequest(0xc000f0d6c0, 0x9, 0x12a05f200, 0xc000b4cf68, 0x20c1540, 0xc0007f9dc0, 0x40ed2d, 0x256ff80, 0xc000ccde00)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/client/client.go:134 +0x17d
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/client.(*Client).SendRequest(0xc000f0d6c0, 0xc000b4cf68, 0x20c1540, 0xc0007f9dc0, 0xf, 0xc000b2c700, 0x3f)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/client/client.go:74 +0xce
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/client.(*Client).Post(0xc000f0d6c0, 0xc001022870, 0xf, 0x20c1580, 0xc000ad0140, 0x20c1540, 0xc0007f9dc0, 0x0, 0x0, 0x0, ...)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/client/client.go:178 +0x205
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/api/globaltagging/globaltaggingv3.(*tags).AttachTags(0xc00000f4c0, 0xc000ada380, 0x79, 0xc000ad0100, 0x4, 0x4, 0x0, 0x4, 0x4, 0x2573340, ...)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/api/globaltagging/globaltaggingv3/tagging.go:80 +0x1d6
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/terraform-provider-ibm/ibm.UpdateTagsUsingCRN(0x2573340, 0xc0007f9ce0, 0x2573340, 0xc0007f9c20, 0x2625920, 0xc000701c00, 0xc000ada380, 0x79, 0x0, 0xc0007828c0)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/structures.go:1682 +0x482
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/terraform-provider-ibm/ibm.instanceCreate(0xc00035b0a0, 0x2625920, 0xc000701c00, 0xc000f11617, 0x7, 0xc0005727e0, 0x24, 0xc000572b10, 0x29, 0xc000f116a0, ...)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/resource_ibm_is_instance.go:829 +0x19d5
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/terraform-provider-ibm/ibm.resourceIBMisInstanceCreate(0xc00035b0a0, 0x2625920, 0xc000701c00, 0x2, 0x3825620)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/resource_ibm_is_instance.go:856 +0x414
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000769900, 0xc000e82780, 0xc000f4c840, 0x2625920, 0xc000701c00, 0x229ff01, 0xc000b40678, 0xc000b9ff50)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.6.0/helper/schema/resource.go:305 +0x375
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0009f4500, 0xc000b4da10, 0xc000e82780, 0xc000f4c840, 0xc000ba0988, 0xc00026dd18, 0x22a3020)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.6.0/helper/schema/provider.go:294 +0x99
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000ad498, 0x2a49a00, 0xc00082aed0, 0xc000cf5800, 0xc0000ad498, 0xc00082aed0, 0xc0012b2b78)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.6.0/internal/helper/plugin/grpc_provider.go:885 +0x8ab
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x2584f40, 0xc0000ad498, 0x2a49a00, 0xc00082aed0, 0xc000cf56e0, 0x0, 0x2a49a00, 0xc00082aed0, 0xc00030b800, 0x1529)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.6.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x214
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00049d200, 0x2a605a0, 0xc0002a1500, 0xc000516400, 0xc00053a330, 0x37c40c0, 0x0, 0x0, 0x0)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1024 +0x522
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: google.golang.org/grpc.(*Server).handleStream(0xc00049d200, 0x2a605a0, 0xc0002a1500, 0xc000516400, 0x0)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1313 +0xd34
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0003ca300, 0xc00049d200, 0x2a605a0, 0xc0002a1500, 0xc000516400)
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:722 +0xa5
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: created by google.golang.org/grpc.(*Server).serveStreams.func1
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.781Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:720 +0xa5
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.785Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/ibm-cloud/ibm/1.20.1/linux_amd64/terraform-provider-ibm_v1.20.1 pid=174 error="exit status 2"
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [DEBUG] ibm_is_instance.fgt1: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] eval: *terraform.EvalMaybeTainted
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] EvalMaybeTainted: ibm_is_instance.fgt1 encountered an error during creation, so it is now marked as tainted
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] eval: *terraform.EvalWriteState
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] EvalWriteState: removing state object for ibm_is_instance.fgt1
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] eval: *terraform.EvalApplyProvisioners
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] EvalApplyProvisioners: ibm_is_instance.fgt1 has no state, so skipping provisioners
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] eval: *terraform.EvalMaybeTainted
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] EvalMaybeTainted: ibm_is_instance.fgt1 encountered an error during creation, so it is now marked as tainted
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] eval: *terraform.EvalWriteState
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] EvalWriteState: removing state object for ibm_is_instance.fgt1
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] eval: *terraform.EvalIf
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] eval: *terraform.EvalIf
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] eval: *terraform.EvalWriteDiff
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] eval: *terraform.EvalApplyPost
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] [walkApply] Exiting eval tree: ibm_is_instance.fgt1
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] vertex "ibm_is_instance.fgt1": visit complete
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.785Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] dag/walk: upstream of "output.FGT1_Default_Admin_Password (expand)" errored, so skipping
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] dag/walk: upstream of "ibm_is_floating_ip.publicip" errored, so skipping
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] dag/walk: upstream of "output.FortiGate_Public_IP (expand)" errored, so skipping
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [DEBUG] ibm_is_instance.fgt2: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] eval: *terraform.EvalMaybeTainted
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] EvalMaybeTainted: ibm_is_instance.fgt2 encountered an error during creation, so it is now marked as tainted
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] eval: *terraform.EvalWriteState
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] dag/walk: upstream of "ibm_is_floating_ip.publicip2" errored, so skipping
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] EvalWriteState: removing state object for ibm_is_instance.fgt2
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] eval: *terraform.EvalApplyProvisioners
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] EvalApplyProvisioners: ibm_is_instance.fgt2 has no state, so skipping provisioners
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] dag/walk: upstream of "output.FGT1_Public_HA_Mangment_IP (expand)" errored, so skipping
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] eval: *terraform.EvalMaybeTainted
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] EvalMaybeTainted: ibm_is_instance.fgt2 encountered an error during creation, so it is now marked as tainted
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] eval: *terraform.EvalWriteState
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] EvalWriteState: removing state object for ibm_is_instance.fgt2
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] eval: *terraform.EvalIf
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] eval: *terraform.EvalIf
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] eval: *terraform.EvalWriteDiff
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] eval: *terraform.EvalApplyPost
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] [walkApply] Exiting eval tree: ibm_is_instance.fgt2
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] vertex "ibm_is_instance.fgt2": visit complete
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] dag/walk: upstream of "ibm_is_floating_ip.publicip3" errored, so skipping
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] dag/walk: upstream of "output.FGT2_Public_HA_Mangment_IP (expand)" errored, so skipping
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] dag/walk: upstream of "output.FGT2_Default_Admin_Password (expand)" errored, so skipping
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/ibm-cloud/ibm\"] (close)" errored, so skipping
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] dag/walk: upstream of "root" errored, so skipping
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] statemgr.Filesystem: have already backed up original terraform.tfstate to terraform.tfstate.backup on a previous write
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 38
 2021/06/21 12:23:33 Terraform apply | 2021/06/21 12:23:33 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
 2021/06/21 12:23:33 Terraform apply | 2021-06-21T12:23:33.789Z [DEBUG] plugin: plugin exited
 2021/06/21 12:23:33 Terraform apply | 
 2021/06/21 12:23:33 Terraform apply | 
 2021/06/21 12:23:33 Terraform apply | 
 2021/06/21 12:23:33 Terraform apply | !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
 2021/06/21 12:23:33 Terraform apply | 
 2021/06/21 12:23:33 Terraform apply | Terraform crashed! This is always indicative of a bug within Terraform.
 2021/06/21 12:23:33 Terraform apply | A crash log has been placed at "crash.log" relative to your current
 2021/06/21 12:23:33 Terraform apply | working directory. It would be immensely helpful if you could please
 2021/06/21 12:23:33 Terraform apply | report the crash with Terraform[1] so that we can fix this.
 2021/06/21 12:23:33 Terraform apply | 
 2021/06/21 12:23:33 Terraform apply | When reporting bugs, please include your terraform version. That
 2021/06/21 12:23:33 Terraform apply | information is available on the first line of crash.log. You can also
 2021/06/21 12:23:33 Terraform apply | get it by running 'terraform --version' on the command line.
 2021/06/21 12:23:33 Terraform apply | 
 2021/06/21 12:23:33 Terraform apply | SECURITY WARNING: the "crash.log" file that was created may contain 
 2021/06/21 12:23:33 Terraform apply | sensitive information that must be redacted before it is safe to share 
 2021/06/21 12:23:33 Terraform apply | on the issue tracker.
 2021/06/21 12:23:33 Terraform apply | 
 2021/06/21 12:23:33 Terraform apply | [1]: https://github.com/hashicorp/terraform/issues
 2021/06/21 12:23:33 Terraform apply | 
 2021/06/21 12:23:33 Terraform apply | !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
 2021/06/21 12:23:33 Terraform APPLY error: Terraform APPLY errorexit status 1
 2021/06/21 12:23:33 Could not execute action
Copy to clipboard
Scroll to top

**Comment by Joel-Cripps** [comment]
Thanks, That's a nasty error. It looks like you hit some sort of kernel panic or something. This isn't an error I can help with. What I would recommend is that you try to delete that workspace, and then recreate. Try a different region if needed. 

We have noted in the past that when terraform encounters an issue like this that sometimes the workspace can't be destroyed. If that happens you will need to contact IBM support.

Alternatively, You could try to deploy with terraform cli and just add in the variables you need to the vars.tf file. But for this you will need to be comfortable with Terraform.

**Comment by jamie-pate** [comment]
If you look at the bottom of the error message, it recommends reporting this issue to terraform directly:
```
Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.
```

**Comment by jamie-pate** [comment]
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2822
