### ISSUE TITLE
Incorrect Interface Naming

### ISSUE THREAD

**Issue by csciarri** [fortinet/ibm-fortigate-AP-HA-terraform-deploy#5]
I deployed the Fortigate VNF in my VPC and noticed that the interface names in the VPC for the Port 3 heartbeat and Port 4 mgmt are reversed. I can see the issue on line 54 and 62 of the instance.tf file.

**Comment by Joel-Cripps** [comment]
Thanks Chris, looks like it. I'll push an update.
